language: php
services:
  - mongodb
php:
  - 7.3
  - 7.4
before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - composer install -n
script:
  - ./vendor/bin/phpunit Tests/
